### ISSUE TITLE
[Crash] file picker crashed when click "TEST FILEPICKER PICK" button

### ISSUE THREAD

**Issue by lmnbeyond** [albertut/cordova-filepicker#1]
First, thank you so much for making this awesome plugin!

Unfortunately, I ran into a problem when I integrate "file picker" plugin into the newest Cordova. I can run "index.html" successfully,but when I click "TEST FILEPICKER PICK" or "TEST FILEPICKER SAVE" button, it crashed. It seems that there is something wrong with "FPPickerController"  or "FPSaveController".

Can you guys help me get my head around this?

Thank you again!

**Comment by lmnbeyond** [comment]
Sorry, it's my fault :(

I missed the following step:
In the project plist add a key: "Filepicker API Key" with a value equal to your key from filepicker.io.

After I add "Filepicker API Key" in the project plist, everything goes well :)

**Comment by albertut** [comment]
Awesome! Sorry I was out of touch, let me know if you have any more problems.
