### ISSUE TITLE
FPSourceBox doesn't seem to work?

### ISSUE THREAD

**Issue by macsharp** [albertut/cordova-filepicker#3]
Hi!
First of all, thanks for the AWESOME plugin! Everything's working fine, except for the FPSourceBox option. All other sources show up without a problem, but the Box option doesn't appear at all.

Could you please check into that? Thank you very much!

CM

**Comment by macsharp** [comment]
Found the issue. In the CDVFilepicker.m line 40 or so, the FPSourceBox condition is missing. Simply add something like this:

``` ObjectiveC
            else if ([source isEqualToString:@"FPSourceBox"])
                addSource = FPSourceBox;
```

And it'll work out just fine.

**Comment by albertut** [comment]
Awesome!  I'll try and fix it this week but if you want to submit a pull request I'll merge it in.  Thanks!
